import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { HomePage } from "src/pages/homepage";
import App from "src/app/App";
import "src/index.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <App />
      </main>
    </>
  );
}
